Payroll/Payroll.MVC/Controllers/SalaryComponentController.cs
using Payroll.Repository;
using Payroll.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Payroll.MVC.Controllers
{
    public class SalaryComponentController : Controller
    {
        // GET: SalaryComponent
        public ActionResult Index()
        {
            return View();
        }

        //GET LIST
        public ActionResult List()
        {
            return View("_List", SalaryComponentRepo.Get());
        }

        public ActionResult Create()
        {            
            return View("_Create");
        }

        //POST CREATE
        [HttpPost]
        public ActionResult Create(SalaryComponentViewModel model)
        {
            if (ModelState.IsValid)
            {
                Responses responses = (SalaryComponentRepo.Update(model));
                if (responses.Success)
                {
                    return Json(new { success = true }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, message = "Error msg" }, JsonRequestBehavior.AllowGet);
                }
            }
            return Json(new { success = false, message = "Invalid" }, JsonRequestBehavior.AllowGet);
        }

        //GET Edit
        public ActionResult Edit(int id)
        {            
            return View("_Edit", SalaryComponentRepo.GetById(id));
        }

        //POST EDIT
        [HttpPost]
        public ActionResult Edit(SalaryComponentViewModel model)
        {
            if (ModelState.IsValid)
            {
                Responses responses = (SalaryComponentRepo.Update(model));
                if (responses.Success)
                {
                    return Json(new { success = true }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, message = responses.Message }, JsonRequestBehavior.AllowGet);
                }
            }
            return Json(new { success = false, message = "Invalid" }, JsonRequestBehavior.AllowGet);
        }

        //GET DELETE
        public ActionResult Delete(int id)
        {
            return View("_Delete", SalaryComponentRepo.GetById(id));
        }

        //POST DELETE
        [HttpPost]
        public ActionResult DeleteConfirm(int id)
        {
            Responses responses = (SalaryComponentRepo.Delete(id));
             if (responses.Success)
            {
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { success = false, message = responses.Message }, JsonRequestBehavior.AllowGet);
        }
        
    }
}

Payroll/Payroll.MVC/Views/SalaryComponent/Index.cshtml
@{
    ViewBag.Title = "Salary Component";
}


<div class="box">
    <div class="box-header">
        <div class="row">
            <div class="col-md-6">

                <button type="button" id="btn-Create" class="btn btn-lg btn-success">
                    Create New
                </button>
            </div>
        </div>
    </div>
    <div class="box-body">
        <div class="row">
            <div class="col-lg-12" id="table-list">
                <h4>Loading...</h4>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="modal-Form">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>

        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

@section Scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            //alert("Masuk");
            ShowList();
        })

        function ShowList()
        {
            $.ajax({
                url: '@Url.Action("List","SalaryComponent")',
                type: 'get',
                success: function (result) {
                    $("#table-list").html(result);
                }
            })
        }

        $("#btn-Create").click(function () {
            $.ajax({
                url: '@Url.Action("Create","SalaryComponent")',
                type: 'get',
                success: function (result) {
                    $(".modal-body").html(result);
                    $(".modal-title").html("Create New Salary Component");
                    $("#modal-Form").modal("show");
                }
            })
        })

    </script>
}

Payroll/Payroll.MVC/Views/SalaryComponent/_Create.cshtml
@model Payroll.ViewModel.SalaryComponentViewModel

@{
    Layout = "";
}

@using (Html.BeginForm("Create", "SalaryComponent", FormMethod.Post, new { id = "create-form", name = "create-form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Period, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.RadioButtonFor(model => model.Period, "D") Daily | @Html.RadioButtonFor(model => model.Period, "M") Monthly
                @*@Html.EditorFor(model => model.Period, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Period, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.RadioButtonFor(model => model.Type, "I") Income | @Html.RadioButtonFor(model => model.Type, "D") Deduction
                @*@Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActivated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActivated)
                    @Html.ValidationMessageFor(model => model.IsActivated, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
    $(".datepicker").datepicker({
        format: 'dd M yyyy'
    })
    $("#create-form").submit(function () {
        $.ajax({
            url: '@Url.Action("Create","SalaryComponent")',
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    $("#modal-Form").modal("hide");
                    ShowList(); // refresh, memanggil #table-list
                }
                else {
                    alert("Error : " + result.message);
                }

            }
        })
        return false;
    })

</script>

Payroll/Payroll.MVC/Views/SalaryComponent/_Delete.cshtml
@model Payroll.ViewModel.SalaryComponentViewModel

@{ 
    Layout = "";
}

<h3>Are you sure you want to delete this?</h3>
<div>    
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Period)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Period)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PeriodName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PeriodName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActivated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActivated)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <button type="button" class="btn btn-danger btn-Delete-Confirm" data-id="@Model.Id">
                Delete
            </button>

            <button type="button" class="btn btn-default" data-dismiss="modal">
                Cancel
            </button>
        </div>
    }
</div>

<script type="text/javascript">

    $(".btn-Delete-Confirm").click(function () {

        $.ajax({
            url: '@Url.Action("DeleteConfirm","Employee")',
            type: "post",
            data: { id : $(this).attr("data-id") },
            success: function (result) {
                if (result.success) {
                    $("#modal-Form").modal("hide");
                    ShowList(); // refresh, memanggil #table-list
                }
                else {
                    alert("Error : " + result.message);
                }

            }
        })
    })

</script>

Payroll/Payroll.MVC/Views/SalaryComponent/_Edit.cshtml
@model Payroll.ViewModel.SalaryComponentViewModel

@{
    Layout = "";
}

@using (Html.BeginForm("Edit", "SalaryComponent", FormMethod.Post, new { id = "edit-form", name = "edit-form" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SalaryComponentViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Period, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.RadioButtonFor(model => model.Period, "D") Daily | @Html.RadioButtonFor(model => model.Period, "M") Monthly
                @*@Html.EditorFor(model => model.Period, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Period, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.RadioButtonFor(model => model.Type, "I") Income | @Html.RadioButtonFor(model => model.Type, "D") Deduction
                @*@Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActivated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActivated)
                    @Html.ValidationMessageFor(model => model.IsActivated, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}


    @Scripts.Render("~/bundles/jqueryval")
<script type="text/javascript">
    
    $("#edit-form").submit(function () {
        $.ajax({
            url: '@Url.Action("Edit","SalaryComponent")',
            type: this.method,
            data : $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    $("#modal-Form").modal("hide");
                    ShowList(); // refresh, memanggil #table-list
                }
                else {
                    alert("Error : " + result.message);
                }

            }
        })
        return false;
    })

</script>

Payroll/Payroll.MVC/Views/SalaryComponent/_List.cshtml
@model IEnumerable<Payroll.ViewModel.SalaryComponentViewModel>

@{
    Layout = "";
}
<table class="table" id="data-list">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PeriodName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TypeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActivated)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PeriodName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TypeName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsActivated)
                </td>
                <td>
                    <div class="btn-group btn-group-sm">
                        <button type="button" class="btn btn-warning btn-Edit" data-id="@item.Id" title="Edit">
                            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                        </button>
                        <button type="button" class="btn btn-danger btn-Delete" data-id="@item.Id" title="Delete">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        </button>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
<script type="text/javascript">
    $("#data-list").DataTable();
    $(".btn-Edit").click(function () {
        //alert($(this).attr("data-id"));

        $.ajax({
            url: '@Url.Action("Edit","SalaryComponent")',
            type: 'get',
            data: { id: $(this).attr("data-id") },
            success: function (result) {
                $(".modal-body").html(result);
                $(".modal-title").html("Edit Employee");
                $("#modal-Form").modal("show");
            }
        })
    })

    $(".btn-Delete").click(function () {
        //alert($(this).attr("data-id"));

        $.ajax({
            url: '@Url.Action("Delete","SalaryComponent")',
            type: 'get',
            data: { id: $(this).attr("data-id") },
            success: function (result) {
                $(".modal-body").html(result);
                $(".modal-title").html("Delete Employee");
                $("#modal-Form").modal("show");
            }
        })
    })

</script>