Payroll/Payroll.MVC/Controllers/PayrollController.cs
using Payroll.Repository;
using Payroll.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Payroll.MVC.Controllers
{
    [Authorize]
    public class PayrollController : Controller
    {
        // GET: Payroll
        public ActionResult Index()
        {
            PayrollPeriodViewModel period = PayrollPeriodRepo.SelectedPeriod;
            if (period != null )
            {
                if (period.Id > 0)
                {
                    return View();
                }
                
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult EmployeeInfo(string badgeId)
        {
            EmployeeViewModel employee = EmployeeRepo.GetByBadgeId(badgeId);
            if (employee == null)
            {
                employee = new EmployeeViewModel();

            }
            return PartialView("_EmployeeInfo", employee);
        }

        public ActionResult EmployeeExist(string badgeId)
        {
            EmployeeViewModel employee = EmployeeRepo.GetByBadgeId(badgeId);
            if (employee != null)
            {
                return Json(new { Exist = true }, JsonRequestBehavior.AllowGet);

            }
            return Json(new { Exist = false }, JsonRequestBehavior.AllowGet);

        }

        public ActionResult EmployeeList(string searching)
        {
            return PartialView("_EmployeeList", EmployeeRepo.GetBySearching(searching));
        }

        public ActionResult EmployeePayroll(string badgeId)
        {
            List <EmployeeSalaryViewModel> empSalary = EmployeeSalaryRepo.GetByBadgeId(badgeId);
            return PartialView("_EmployeePayroll", empSalary) ;
        }

        public ActionResult SalaryComponentList()
        {
            return PartialView("_SalaryComponentList", SalaryComponentRepo.Get());
        }

        //buat ambil value di payroll
        public ActionResult GetSalaryComponent(int jobPositionId, int salaryComponentId)
        {
            EmployeeSalaryViewModel model = EmployeeSalaryRepo.GetByComponentId(salaryComponentId);
            SalaryDefaultValueViewModel sd = SalaryDefaultValueRepo.GetByJobPositionId(jobPositionId, salaryComponentId);
            if (sd != null)
            {
                model.BasicValue = sd.Value;
            }
            return PartialView("_GetSalaryComponent", model);
        }

        [HttpPost]
        public ActionResult SavePayroll(List<EmployeeSalaryViewModel> models)
        {
            Responses responses = EmployeeSalaryRepo.SaveSalary(models);

            return Json(new { response = responses }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult RemoveComponent(string bId, int scId)
        {
            List<EmployeeSalaryViewModel> models = EmployeeSalaryRepo.GetByBadgeId(bId, scId);
            if (models.Count > 0)
            {
                EmployeeSalaryViewModel model = models[0];
                return PartialView("_RemoveComponent", model);
            }
            return PartialView("_RemoveComponent", new EmployeeSalaryViewModel());
        }

        [HttpPost]
        public ActionResult RemoveConfirm(int id)
        {
            Responses responses = EmployeeSalaryRepo.RemoveByComponentId(id);
            if (responses.Success)
            {
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false, message = "Error msg" }, JsonRequestBehavior.AllowGet);
        }

    }
}

Payroll/Payroll.MVC/Views/Payroll/Index.cshtml
@{
    ViewBag.Title = "Payroll Form";
}

<div class="box">
    <div class="box-header">
        <div class="row">
            <div class="col-md-6">
                <input type="text" id="txt-search" placeholder="Input NIP..." />
                <button type="button" id="btn-search" class="btn btn-default btn-danger">
                    Search
                </button>
            </div>
        </div>
    </div>
    <div class=" box-body">
        <div class="row">
            <div class="col-lg-12" id="employee-info">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <button type="button" id="btn-add" class="btn btn-default btn-success">
                    Add Component
                </button>
                <button type="button" id="btn-save" class="btn btn-default btn-info">
                    Save Salary
                </button>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th> Code</th>
                            <th> Salary Component </th>
                            <th> Basic Value </th>
                            <th> Final Value</th>
                            <th> Action</th>
                        </tr>
                    </thead>
                    <tbody id="employee-payroll">
                        <tr>
                            <td>

                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="modal-Form">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

@section Scripts
    {
    <script type="text/javascript">
        $(document).ready(function () {
            EmployeeInfo("");
        })

        var RemoveObject = null;

        function EmployeeInfo(bId) {
            $.ajax({
                url: '@Url.Action("EmployeeInfo", "Payroll")',
                type: 'get',
                data: { badgeId: bId },
                success: function (result) {
                    $("#employee-info").html(result);
                }
            })
        }

        $("#btn-search").click(function () {
            var bId = $("#txt-search").val();
            var search = $("#txt-search").val();
            $.ajax({
                url: '@Url.Action("EmployeeExist", "Payroll")',
                type: 'get',
                data: { badgeId: bId },
                success: function (result) {
                    if (result.Exist) {
                        EmployeeInfo(bId);
                        EmployeePayroll(bId);
                    }
                    else {
                        GetEmployeeList(search);
                    }
                }
            })
        })

        function GetEmployeeList(search)
        {
            $.ajax({
                url: '@Url.Action("EmployeeList", "Payroll")',
                type: 'get',
                data: { searching: search },
                success: function (result) {
                    $(".modal-body").html(result);
                    $(".modal-title").html("List Employee");
                    $("#modal-Form").modal("show");
                }
            })
        }

        function EmployeePayroll(bId) {
            $.ajax({
                url: '@Url.Action("EmployeePayroll", "Payroll")',
                type: 'get',
                data: { badgeId: bId },
                success: function (result) {
                    $("#employee-payroll").html(result);
                }
            })
        }

        $("#btn-add").click(function () {
            //alert("jsdhsdha");
            $.ajax({
                url: '@Url.Action("SalaryComponentList", "Payroll")',
                type: 'get',

                success: function (result) {
                    $(".modal-body").html(result);
                    $(".modal-title").html(" List Salary Component");
                    $("#modal-Form").modal("show");
                }
            })
        })

        function Remove(obj)
        {
            var tr = $(obj).closest("tr");
            RemoveObject = tr;
            var badgeId = $("#BadgeId").val();
            var ppId = @Payroll.Repository.PayrollPeriodRepo.SelectedPeriod.Id;
            var scId = $(tr).find("input[name=SalaryComponentId]").val();
            
            var data = {
                BadgeId : badgeId,
                PayrollPeriodId : ppId,
                SalaryComponentId : scId
            }
            
            $.ajax({
                url: '@Url.Action("RemoveComponent", "Payroll")',
                type: 'get',
                data : { bId: badgeId, scId: scId},
                success: function (result) {
                    $(".modal-body").html(result);
                    $(".modal-title").html("Remove Component");
                    $("#modal-Form").modal("show");
                }
            })
                
        }


        $("#btn-save").click(function () {
            //alert("jsdhsdha");
            var dataList = [];
            var badgeId = $("#BadgeId").val();
            var ppId = @Payroll.Repository.PayrollPeriodRepo.SelectedPeriod.Id;
            $("#employee-payroll").find("tr").each(function(){

                var scId = $(this).find("input[name=SalaryComponentId]").val();
                var basVal = $(this).find("input[name=BasicValue]").val();
                var data = {
                    BadgeId : badgeId,
                    PayrollPeriodId : ppId,
                    SalaryComponentId : scId,
                    BasicValue : basVal,


                }
                dataList.push(data);
            })
            //alert (JSON.stringify(dataList));
            $.ajax({
                url: '@Url.Action("SavePayroll", "Payroll")',
                type: 'post',
                data : {models : dataList},
                success: function (result) {
                    if (result.response.Success) 
                    {
                        alert("Success bos");
                    }
                    else {
                        alert("Error bos");
                    }
                   
                }
            })

        })

        function RemoveComponent(){
            if (RemoveObject != null) {
                $(RemoveObject).remove();
            }
        }

    </script>
}

Payroll/Payroll.MVC/Views/Payroll/_EmployeeInfo.cshtml
@model Payroll.ViewModel.EmployeeViewModel

<div class="row">
    <div class="col-lg-6">
        <div class="form-group">
            @Html.LabelFor(model => model.BadgeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BadgeId, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="form-group">
            @Html.LabelFor(model => model.JobName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.JobPositionId)
                @Html.EditorFor(model => model.JobName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-6">
        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="form-group">
            @Html.LabelFor(model => model.DateOfHire, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfHire, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
    </div>
</div>

Payroll/Payroll.MVC/Views/Payroll/_EmployeeList.cshtml
@model IEnumerable<Payroll.ViewModel.EmployeeViewModel>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
<table class="table">
    <tr>
        <th>Select</th>
        <th>
            @Html.DisplayNameFor(model => model.BadgeId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfHire)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <button type="button" class="btn btn-success btn-Select" data-id="@item.Id" data-badgeId="@item.BadgeId">
                    Select
                </button>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BadgeId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JobName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfHire)
            </td>

        </tr>
    }
</table>

<script type="text/javascript">
    $(".btn-Select").click(function () {
        //alert($(this).attr("data-badgeId"));
        EmployeeInfo($(this).attr("data-badgeId"));
        EmployeePayroll($(this).attr("data-badgeId"));
        $("#modal-Form").modal("hide");
    })
</script>

Payroll/Payroll.MVC/Views/Payroll/_EmployeePayroll.cshtml
@model IEnumerable<Payroll.ViewModel.EmployeeSalaryViewModel>


@foreach (var item in Model)
{
    @Html.Partial("_GetSalaryComponent", item)
}

Payroll/Payroll.MVC/Views/Payroll/_GetSalaryComponent.cshtml
@model Payroll.ViewModel.EmployeeSalaryViewModel
<tr>
    <td>
        @Html.HiddenFor(model => model.SalaryComponentId) @Html.EditorFor(model => model.SalaryComponentCode, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
    </td>
    <td>
        @Html.EditorFor(model => model.SalaryComponentName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
    </td>
    <td>
        @Html.EditorFor(model => model.BasicValue, new { htmlAttributes = new { @class = "form-control" } })
    </td>
    <td>
        @Html.EditorFor(model => model.FinalValue, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
    </td>
    <td>
        <button type="button" class="btn btn-sm btn-danger btn-remove" onclick="Remove(this)">
            Delete
        </button>
    </td>
</tr>

Payroll/Payroll.MVC/Views/Payroll/_RemoveComponent.cshtml
@model Payroll.ViewModel.EmployeeSalaryViewModel

<h3>Are you sure you want to delete this?</h3>
<div>
    
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BadgeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BadgeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PayrollPeriodId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PayrollPeriodId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SalaryComponentId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SalaryComponentId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SalaryComponentCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SalaryComponentCode)
        </dd>

       

        <dt>
            @Html.DisplayNameFor(model => model.BasicValue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BasicValue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FinalValue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FinalValue)
        </dd>

       

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <button type="button" class="btn btn-danger btn-Delete-Confirm" data-id="@Model.Id" data-badgeId="@Model.BadgeId">
                Delete
            </button>

            <button type="button" class="btn btn-default" data-dismiss="modal">
                Cancel
            </button>
           
        </div>
    }
</div>

<script type="text/javascript">

    $(".btn-Delete-Confirm").click(function () {
        var badgeId = $(this).attr("data-id");
        if ($(this).attr("data-id") == "0") {
            $("#modal-Form").modal("hide");
            RemoveComponent();
        }
        else {
            $.ajax({
                url: '@Url.Action("RemoveConfirm","Payroll")',
                type: "post",
                data: { id: $(this).attr("data-id") },
                success: function (result) {
                    if (result.success) {
                        $("#modal-Form").modal("hide");
                        RemoveComponent();
                    }
                    else {
                        alert("Error : " + result.message);
                    }

                }
            })
        }
       
    })

</script>

Payroll/Payroll.MVC/Views/Payroll/_SalaryComponentList.cshtml
@model IEnumerable<Payroll.ViewModel.SalaryComponentViewModel>


<table class="table">
    <tr>
        <th>Select</th>
        <th>
            @Html.DisplayNameFor(model => model.Code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
       
        <th>
            @Html.DisplayNameFor(model => model.PeriodName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
      
       
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <button type="button" class="btn btn-success btn-Select" data-id="@item.Id">
                Select
            </button>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.PeriodName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Type)
        </td>
     
       
    </tr>
}

</table>

<script type="text/javascript">
    $(".btn-Select").click(function () {
        //alert($(this).attr("data-id"));
       
        $.ajax({
            url: '@Url.Action("GetSalaryComponent", "Payroll")',
            type: 'get',
            data: { jobPositionId: $("#JobPositionId").val(), salaryComponentId: $(this).attr("data-id") },
            success: function (result) {
                $("#employee-payroll").append(result);
                
                $("#modal-Form").modal("hide");
            }
        })
       
    })
</script>